eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
server:
  port: 8084
spring:
  application:
    name: gateway
  cloud:
    # Configuration de l'API Gateway
    gateway:
      discovery:
        locator:
          enabled: true #activation eureka locator
          lowerCaseServiceId: true
          # car le nom des services est en minuscule dans l'URL
      # Configuration des routes de l'API Gateway
      routes:
        #Service 1
        - id: utilisateur
          uri: lb://UTILISATEUR/
          predicates:
            # On matche tout ce qui commence par /api/toto
            - Path=/api/utilisateurs/**
          filters:
            # On va réécrire l'URL pour enlever le /api/toto
            - RewritePath=/api/utilisateurs(?<segment>/?.*), /$\{segment}
        #Service 2
        #- id: creneau
        #  uri: lb://COMPTE/
        #  predicates:
        #    - Path=/api/comptes/**
        #  filters:
            # On va réécrire l'URL pour enlever le /api/toto
        #    - RewritePath=/api/comptes(?<segment>/?.*), /$\{segment}
        #Service 3
        #- id: composite
        #  uri: lb://COMPOSITE/
        #  predicates:
        #    - Path=/api/clientComptes/**
        #  filters:
            # On va réécrire l'URL pour enlever le /api/toto
        #    - RewritePath=/api/clientComptes(?<segment>/?.*), /$\{segment}