eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
server:
  port: 8084
spring:
  application:
    name: gateway
  cloud:
    # Configuration de l'API Gateway
    gateway:
      discovery:
        locator:
          enabled: true #activation eureka locator
          lowerCaseServiceId: true
          # car le nom des services est en minuscule dans l'URL
      # Configuration des routes de l'API Gateway
      routes:
        #Service 1
        - id: utilisateur
          uri: lb://UTILISATEUR/
          predicates:
            # On matche tout ce qui commence par /api/toto
            - Path=/api/utilisateurs/**
          filters:
            # On va réécrire l'URL pour enlever le /api/toto
            - RewritePath=/api/utilisateurs(?<segment>/?.*), /$\{segment}
        #Service 2
        - id: creneau
          uri: lb://CRENEAU/
          predicates:
            - Path=/api/creneau/**
          filters:
          # On va réécrire l'URL pour enlever le /api/toto
            - RewritePath=/api/creneau(?<segment>/?.*), /$\{segment}
        #Service 3
        - id: badge
          uri: lb://BADGE/
          predicates:
            - Path=/api/badge/**
          filters:
            # On va réécrire l'URL pour enlever le /api/toto
            - RewritePath=/api/badge(?<segment>/?.*), /$\{segment}
          #Service 4
          - id: statistique
            uri: lb://STATISTIQUE/
            predicates:
              - Path=/api/statistique/**
            filters:
              # On va réécrire l'URL pour enlever le /api/toto
              - RewritePath=/api/statistique(?<segment>/?.*), /$\{segment}