spring:
  application:
    name: utilisateur
  data:
    mongodb:
      database: odoru
      username: root
      password: admin
      authentication-database: admin
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
